### ISSUE TITLE
DOM XSS - Documentation

### ISSUE THREAD

**Issue by ghost** [jmanico/owasp-java-encoder#13]
I think we need to make clear somewhere in the documentation clear that customers need to take additional steps for preventing DOM based XSS when using this library. Current documentation says about how to encode in direct CSS/HTML contexts but does not talk about how to encode when inserting Untrusted Data into HTML Subcontext within the Execution Context.

There are many such examples in [1] and I think its worth it to make a note of it somewhere in the documentation of this document.

[1] https://www.owasp.org/index.php/DOM_based_XSS_Prevention_Cheat_Sheet#RULE_.231_-_HTML_Escape_then_JavaScript_Escape_Before_Inserting_Untrusted_Data_into_HTML_Subcontext_within_the_Execution_Context

**Comment by jmanico** [comment]
This library is for encoding only. It does not do HTML sanitization. Also, DOM XSS is best defended against buy using safe JS API’s like .textContent (not escaping). You also need CSP. You should also consider HTTPOnly cookies. And the X-XSS-Protection header.

So we’re not trying to address any of those other defenses; just encoding.

Where do you propose we make it (more) clear this is for encoding only?

Aloha,
—
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by ghost** [comment]
Yup, I get that. 

I am just thinking that people would assume that using this library properly (ie.., using right encoding function)  would help them in mitigating against all sorts of XSS attacks including DOM. In fact, home page [1] says - "This project will help Java web developers defend against Cross Site Scripting!". Even you use all the context sensitive functions correctly, you might still be vulnerable to XSS according to OWASP DOM based prevention wiki as we need to encode for HTML first and then for JS next for few situations. I propose we make this clear either on the homepage.

[1] https://www.owasp.org/index.php/OWASP_Java_Encoder_Project

**Comment by jmanico** [comment]
I’ll add some notes to the wiki about this topic over the weekend. Good call.

Aloha,
--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by jmanico** [comment]
Warning has been added!

https://www.owasp.org/index.php?title=OWASP_Java_Encoder_Project&type=revision&diff=239490&oldid=236044

**Comment by jmanico** [comment]
Assuming the warning is enough, I'm closing this out for now.
