### ISSUE TITLE
unescape functions

### ISSUE THREAD

**Issue by maxmeout** [jmanico/owasp-java-encoder#15]
Do you guys have any plan of including unescape/unencode functions within this library? They will be helpful in few cases (Ex: If I am encoding all my untrusted parameters within requests in my application) and need 1/2 of them to be decoded within my application for some processing before sending it to view?

**Comment by jmanico** [comment]
This is not on our roadmap. Encoding in the context of this library always provides security when used correctly. Decoding can be extremely dangerous in the content of XSS and UI security.

I am sorry for this “no” answer but we’ve discussed it before internally and agreed not to provide decoders for this library.

Respectfully,
--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
We sadly do not plan to implement these features for safety reasons.
