### ISSUE TITLE
Unicode character escapes are encoded again by Encoder.forHtml()

### ISSUE THREAD

**Issue by indra2gurjar** [jmanico/owasp-java-encoder#18]
if the input string contains unicode escaped character e.g. &#9989; 
the output is "& amp ;#9989;"
the '&' character is encoded again.
Does Encoder support unicode escaped characters and it is a bug or this is not supported?

**Comment by jmanico** [comment]
The encoder is meant, on purpose, to encode all dangerous characters like you are describing. This is not the right tool for you.

If you have HTML entities that you wish to preserve then your input is HTML. Consider using the OWASP HTML Sanitizer instead.

Aloha, 
--
Jim Manico
@Manicode

**Comment by jmanico** [comment]
This is not something we can fix, it's about proper use of the library.
