### ISSUE TITLE
Private constructor prevents Encoder from being used in script bindings

### ISSUE THREAD

**Issue by veita** [jmanico/owasp-java-encoder#19]
Due to its private constructor `Encoder` cannot be used in scripting language bindings that require an object.

**Comment by xeno6696** [comment]
Not a lot to go on here, @veita 

Some kind of example code?  I've used this in Grails applications and never had a problem.

**Comment by veita** [comment]
As an example consider access to the `Encoder` via an accessor object in Velocity context.

However, in my case I decided to wrap the `Encoder` in an own class for different null value processing. So this is no longer an issue for me.

**Comment by jmanico** [comment]
Dear @jeffi can you take a look at this please?

**Comment by jmanico** [comment]
Looks like we can close this out.
