### ISSUE TITLE
GoogleCode to GitHub (SVN to Git migration)

### ISSUE THREAD

**Issue by h3xstream** [jmanico/owasp-java-encoder#2]
In order to keep the previous version tagging and commit history, a proper export could be made : 
http://stackoverflow.com/a/79178/89769

**Comment by jmanico** [comment]
We are just happy we got it moved correctly and do not plan to do a formal export. I agree we should have done it that way in the first place... I'm going to close this issue, but if you want to help make this happen I'll open it again and give you access to mess with it....

Respectfully,
Jim
jim@owasp.org
