### ISSUE TITLE
New encoding function needed for template literal context (string literals)

### ISSUE THREAD

**Issue by veita** [jmanico/owasp-java-encoder#22]
`Encode.forJavaScript` is intended to 

> Encode for a JavaScript string. It is safe for use in HTML script attributes (such as onclick), script blocks, JSON files, and JavaScript source. The caller MUST provide the surrounding quotation characters for the string.

However, the string
```java
input = "hell`;alert(1);`o"
```
encoded with `Encode.forJavaScript` produces the following output which allows for XSS.

```html
<!DOCTYPE html>
<html>
  <body>
  <script>
  // var data = `<%=Encode.forJavaScript(input)%>`;
  var data = `hell`;alert(1);`o`;
  </script>
  </body>
</html>
```

Related: https://github.com/OWASP/owasp-java-encoder/issues/14

**Comment by jmanico** [comment]
As documented here you need to quote your var's if you're doing
templated JavaScript
 https://www.owasp.org/index.php/OWASP_Java_Encoder_Project#tab=Use_the_Java_Encoder_Project

 <script type="text/javascript">
 var msg = "<%= *Encode.forJavaScriptBlock(UNTRUSTED)* %>";
 alert(msg);
 </script>

Aloha, Jim

PS: And as a side note, it's really best to put all your JS in separate
JS files as opposed to embedded JS within HTML.

**Comment by veita** [comment]
Sorry, I don't get your point. This issue is about [JavaScript template literals](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-template-literal-lexical-components).

In the example above the template is correctly quoted with grave accent as the surrounding quotation character.

**Comment by jmanico** [comment]
We're not able to handle that kind of use case with our encoding functions.

We only encode similar to the examples provided. So I would not call
this a bypass, but an incorrect use of the library.

I could be wrong; I'll try to get Jeff Ichnowski (the library author) to
take a look.

Aloha, Jim

**Comment by veita** [comment]
I think [RULE #3](https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet#RULE_.233_-_JavaScript_Escape_Before_Inserting_Untrusted_Data_into_JavaScript_Data_Values) of the original OWASP XSS Prevention Cheat Sheet

> Except for alphanumeric characters, escape all characters less than 256 with the \xHH format [...]

would handle this case correctly.

**Comment by jmanico** [comment]
We find that rule to be excessive. We're aiming for low-character,
high-performance encoding for specific cases. I believe what you're
doing is non-standard.

For cases where folks use ' and " quoted JS variables in templated
JavaScript, the current encoding is all that is needed.

Again, I'll talk to Jeff about this.

- Jim

**Comment by veita** [comment]
Template literals are in the JavaScript standard since ECMAScript 2015 Language Specification 6th Edition, June 2015. See the [link ](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-template-literal-lexical-components) I've posted in my first comment above.

**Comment by jmanico** [comment]
This library does not currently support string liberals with the
JavaScript encoding functions. I deleted several of the comments above
to clear up this thread; some of our comments crossed. I follow you now.

I'll add a feature request for a string literal escaping function or
similar and will get Jeff involved.

**Comment by veita** [comment]
Jim, thank you very much.
-Alex

**Comment by jeffi** [comment]
The above use case would be better handled by using strings instead of template literals.  But I assume this is just mentioned as a demonstration, and that there is a valid use case for embedding server side data in a template literal.  An easy way to do it right now would be to embed the server-side string in the template literal by surrounding it with `${"` and `"}` and escaping it.  Hopefully this can provide a useful crutch for now:

```html
<!DOCTYPE html>
<html>
  <body>
  <script>
  // var data = `${"<%=Encode.forJavaScript(input)%>"}`;
  var data = `${"hell`;alert(1);`o"}`;  // does not pop alert
  </script>
  </body>
</html>
```

My recommendation, however, would be to instead escape the content to a JavaScript variable, and then use a template literal that references the variable, e.g.:

```javascript
    var input = "<$= Encode.forJavaScript(input) $>";
    var data = `Here's your input: ${ input }, hope it's not XSS!`;
```

**Comment by jmanico** [comment]
After talking with @jeffi we decided to politely close this out and not add a new encoding method. I'll update the wiki to address this issue per Jeff's comments.

**Comment by jmanico** [comment]
Wiki text added https://www.owasp.org/index.php/OWASP_Java_Encoder_Project#tab=Encoding_and_Template_Literals

**Comment by veita** [comment]
Would there really be the need to create a new encoding method?

From my naive point of view template literals are just a third kind of string literals delimited by backticks instead of single or double quotes.

So my guess is that it would suffice to let the existing `Encode.forJavaScript` output `\x60` for any occurrence of the backtick.
