### ISSUE TITLE
API documentation has incorrect usage for forHtmlAttribute

### ISSUE THREAD

**Issue by thariyarox** [jmanico/owasp-java-encoder#24]
n the API documentation, forHtmlAttribute method's example usage is listed as following.
<%=Encode.forHtml(unsafeData)%>

It should be corrected as following.
<%=Encode.forHtmlAttribute(unsafeData)%>

I have corrected it and sent the PR [2]. Please review and merge.

[1] https://owasp.github.io/owasp-java-encoder/encoder/apidocs/org/owasp/encoder/Encode.html#forHtmlAttribute-java.lang.String-
[2] https://github.com/OWASP/owasp-java-encoder/pull/23

**Comment by jmanico** [comment]
Excellent. We’re planning a “we are still here” point release soon which will include this fix. Thanks for the patch! Love it!

Aloha, 
Jim

**Comment by jmanico** [comment]
Released and is live with version 1.2.2!
