### ISSUE TITLE
FEature: RegEx encoder

### ISSUE THREAD

**Issue by Weltraumschaf** [jmanico/owasp-java-encoder#29]
Just did a quick look through the code and it looks like there is no encoder for RegEx context.

I'm just facing this issue: I have untrusted user input and must escape all RegEx meta characters to avoid possible crashes.

**Comment by VsevolodGolovanov** [comment]
java.util.regex.Pattern.quote(String)?

**Comment by jmanico** [comment]
Example of how this is being used, please? A special encoder should not be necesary.

--
Jim Manico
@Manicode

**Comment by VsevolodGolovanov** [comment]
System.out.println(Pattern.matches("\\w+", "anything")); // true - matches any word

	System.out.println(Pattern.matches(Pattern.quote("\\w+"), "anything")); // false - doesn't match any word
	System.out.println(Pattern.matches(Pattern.quote("\\w+"), "\\w+")); // true - matches only "\w+" literally

**Comment by jmanico** [comment]
We politely cannot support this, we really want to focus on XSS defense in web pages. RegEx escaping is out of bounds for us.
