### ISSUE TITLE
Encoding Supplementary character creates an issue 

### ISSUE THREAD

**Issue by sudarshannavada** [jmanico/owasp-java-encoder#34]
encoder.encodeForHtml of Japanese character “𠮷”( \&#x20BB7; ) resulting in \&#xd842;\&#xdfb7; and these code points are not identified by HTML document.
The browser doesn't understands the surrogate pairs.
We are using     <groupId>org.owasp.esapi</groupId> <artifactId>esapi</artifactId><version>2.1.0.1</version>
and 
ESAPI.Encoder=org.owasp.esapi.reference.DefaultEncoder

Any leads will be appreciated.

**Comment by jmanico** [comment]
You referenced the ESAPI encoder but listed a bug in the OWASP Java Encoder. These are separate projects. Can you try this in the OWASP Java encoder?

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by sudarshannavada** [comment]
Sorry for the mistake, I have tried  org.owasp.encoder.Encode.forHtmlContent(String input) as Javadoc says Surrogate pairs are passed through if valid. 
Anyway I got the solution.. ! 
Thank You.
