### ISSUE TITLE
Create an encodeForEmail() function

### ISSUE THREAD

**Issue by skotfred** [jmanico/owasp-java-encoder#46]
It would seem that a rule for email would not completely match any of the existing rules.  Additionally, this seems to be a value that is an obvious choice for reflected attacks.

**Comment by jmanico** [comment]
Can you give us an exact example of what you want to do? I don't see it 
yet...

Aloha, Jim

**Comment by skotfred** [comment]
Obviously this is an edge case, but one example would be for cases where a user enters "example@<script>alert('xss');</script>domain.com" as it could be reflected back to the output.

**Comment by jmanico** [comment]
Normal output encoding will suffice, we don’t need a special encoder for this. If the email is in an attribute then do attribute encoding, etc.

--
Jim Manico
@Manicode
Secure Coding Education
+1 (808) 652-3805

**Comment by jmanico** [comment]
Normal encoding will work here, politely closing this out.
