### ISSUE TITLE
Javadoc link is broken

### ISSUE THREAD

**Issue by rob-purchase-dotmatics** [jmanico/owasp-java-encoder#53]
The Javadoc link in the Getting Started section of the main project page at https://owasp.org/www-project-java-encoder/ seems to be broken. Does the project still intend to host Javadoc on github.io or should the copy at https://javadoc.io/doc/org.owasp.encoder/encoder/latest/index.html be used instead?

**Comment by jmanico** [comment]
Noted, I'll get this fixed soon

**Comment by jmanico** [comment]
For now I am just going top link to https://javadoc.io/doc/org.owasp.encoder/encoder/latest/index.html is that acceptable?

**Comment by jmanico** [comment]
This fix is live, if I did not fix this as you wanted, please re-open or add more comments here.

**Comment by rob-purchase-dotmatics** [comment]
Looks good, thank you 👍
