### ISSUE TITLE
Confusing example in Encode.forHtmlAttribute docs

### ISSUE THREAD

**Issue by meeque** [jmanico/owasp-java-encoder#71]
Currently the `Encode.forHtmlAttribute` JavaDocs contain [this JSP example](/OWASP/owasp-java-encoder/blob/main/core/src/main/java/org/owasp/encoder/Encode.java#L246):

```
<div><%=Encode.forHtmlAttribute(unsafeData)%></div>
```

I guess this may be secure, but imho it does not reflect the intention of this method. How about using an example that involves html attributes? Maybe something like this:

```
<div title="<%=Encode.forHtmlAttribute(unsafeData)%>">...</div>
<div title='<%=Encode.forHtmlAttribute(unsafeData)%>'>...</div>
```

Imho the JavaDocs should also mention that the caller of this method must add quotes around the outputs of this method.

If you think any of this is helpful, I can prepare a PR.

**Comment by kwwall** [comment]
I agree. That's a Javadoc bug.  I thought that quotes were mentioned as being required somewhere in the `Encode` Javadoc, but I could be wrong about that.

I'd say PR away, but that's not really my call.

**Comment by meeque** [comment]
Well, I've proposed PR #72 to fix this. Feel free to provide feedback...

**Comment by jeremylong** [comment]
PR has been merged. Thanks again for the PR!
