### ISSUE TITLE
Can i compile the project with j2sdk1.4.2_19 

### ISSUE THREAD

**Issue by talasila66** [jmanico/owasp-java-encoder#8]
My application runs over j2sdk1.4.2_19, Can I compile the project with j2sdk1.4.2_19 ? any alternative suggested?

**Comment by jmanico** [comment]
Sadly, no. This project is for Java 5 and above.

Java 1.4 was end of life many many years ago and I caution you that there is rarely a good reason to use it.

--
Jim Manico
@Manicode

**Comment by talasila66** [comment]
Can I pull the code and make it compatible with Java 1.4 and use it?

**Comment by xeno6696** [comment]
Well, it's open source so in theory you can do whatever you want, but Java
1.4 has so many other disasterous security vulnerabilities that doing so
would be like putting a single piece of bubblegum on a damn with 1000
leaks.

You've already lost the battle.

**Comment by xeno6696** [comment]
To put it into perspective there are roughly 550 known CVEs against Java,
and if you're using 1.4 that means you're vulnerable to 75% of them since
the majority of flaws began to be found in 1.6.

**Comment by jmanico** [comment]
Well it’s open source, so yes.

**Comment by talasila66** [comment]
Thank you
