### ISSUE TITLE
owasp encoder with commons-lang3 instead of commons-lang

### ISSUE THREAD

**Issue by chnaahmad** [jmanico/owasp-java-encoder#9]
Hi All,
actually we are moving / upgrading our system to commons-lang3 instead of commons-lang. 
That's why i want to know that "Is owasp Encoder work with commons-lang3?"
currently i am seeing that owasp Encoder has dependency over commons-lang 2. 6.
Would you please help me to sort out this problem.
Naeem

**Comment by jmanico** [comment]
Just want you to know that we got this bug report and are evaluating it.

Aloha, Jim

**Comment by jmanico** [comment]
- The Core of the Java Encoder has zero dependencies
- The JSP encoder taglib only uses the core and

        <dependency>
            <groupId>javax.servlet.jsp</groupId>
            <artifactId>javax.servlet.jsp-api</artifactId>
            <version>2.2.1</version>
            <optional>true</optional>
        </dependency>

- However, if you are using ESAPI that lib (a different project) has several other dependencies.

So no part of The Java encoder should be effected by the upgrade to commons.

**Comment by jmanico** [comment]
So no part of The Java encoder should be effected by the upgrade to commons.
